### ISSUE TITLE
Declare a platform strategy

### ISSUE THREAD

**Issue by Croydon** [inexorgame/code#108]
We have to declare which platforms we are going to support officially. Of course that doesn't mean that other configurations aren't working, but that we aren't going to test them, or to fix bugs for them if there are problems (exceptions possible, one should just not rely on it).

Natural we can only support platforms when we have such testing environments and at least one offical person who is testing on a regulary basis.

There a two categories, the first one are operating systems, with their -exact- versions (keep in mind we have to test them all, when we are saying we supporting them..), the second would be compilers/IDEs, with their -exact- versions.

We have to talk about that and collect the results. Feel free to edit following table:

<b>OS (on which we are testing regulary that Inexor is RUNNING):</b>

<table>
<tr><td><b>Name</b></td><td><b>Version</b></td><td><b>Maintainer(s)</b></td></tr>
<tr><td>Windows </td><td>10 64bit</td><td> ? </td></tr>
<tr><td></td><td>8.1 64bit</td><td> <a href ="https://github.com/a-teammate">a_teammate</a> </td></tr>
<tr><td></td><td>7 64bit</td><td> <a href ="https://github.com/Croydon">Nooby</a> </td></tr>
<tr><td>Ubuntu </td><td>16.04 64bit</td><td> <a href="https://github.com/Fohlen">Fohlen</a>, <a href="http://github.com/aschaeffer">Hanack</a> </td> </td></tr>
<tr><td>Fedora </td><td>24(?) 64bit</td><td> (Nooby, soon)? </td></tr>
<tr><td>Linux Mint </td><td>17.2 64bit</td><td> <a href ="https://github.com/basile-henry">Boomerang</a> </td></tr>
</table>

<b>Note:</b> We are not going to support Windows versions older than Windows 7 or Ubuntu versions older than Ubuntu 16.04. It might work, but no official support.

<b>Compilers/IDEs (on which we are testing regulary that Inexor is BUILDABLE):</b>

<table>
<tr><td><b>Name + Version</b></td><td><b>Maintainer(s)</b></td></tr>
<tr><td>Code::Blocks 16.01 + MinGW W64 4.2.0 with GCC 5.1.0 on Win7 64</td><td><a href ="https://github.com/Croydon">Nooby</a></td></tr>
<tr><td>Eclipse + GCC on Ubuntu 16.04 64bit</td><td><a href="https://github.com/aschaeffer">Hanack</a></td></tr>
<tr><td>Visual Studio 15 Community + Windows 8.1 64bit</td><td><a href="https://github.com/a-teammate">a_teammate</a></td></tr>
<tr><td>GCC on Linux Mint 17.2 64bit</td><td><a href ="https://github.com/basile-henry">Boomerang</a></td></tr>
</table>

<b>Other requirements for RUNNING:</b>

<ul>
    <li>GPU with OpenGL 2.0+ support</li>
</ul>

**Comment by Croydon** [comment]
I would be up for testing on Windows 7 SP1 64bit, and also for the respective latest stable Code::Blocks version in combination with MinGW.

**Comment by IAmNotHanni** [comment]
I can support testing Windows 7 64, Ubuntu and Windows XP

**Comment by Croydon** [comment]
For Ubuntu and similar distributions we have to think about if we want to support only the latest or also the latest LTS version.

About Windows XP: Normally nobody should use it anymore, and definitely not when there is an internet connection, it's just a big bloody security hole. Moreover gamers are often early adopters of new software and hardware. I'm not sure if Windows XP users are really our target audience, however Sauerbraten had for a long time the philosophy to run on very old machines.

**Comment by a-teammate** [comment]
Running and building are 2 seperate things though. It will highly probably run on windows xp as well, while it doesn't mean we should always test it.
just for clarification

**Comment by Croydon** [comment]
@a-teammate Exactly. The OS-table is meant for the OS+version configs, on which Inexor is running AND we are testing regulary. The second table is for Compiler/IDE's setups in which Inexor is buildable AND we are testing regulary.

**Comment by Fohlen** [comment]
I can maintain Ubuntu 14.04 (especially server builts), 15.04 and Arch Linux (which whom I use as desktop systems).
As for Ubuntu we should be keeping a track on the LTS cycle, as Ubuntu will NOT break compatibility until the next LTS release (packages with no version changes, eg: enet will be linked against upstream versions, but not changed/removed).

**Comment by basile-henry** [comment]
I build regularly on Linux Mint 17.2 64bit (LTS based on Ubuntu 14.04) using gcc as compiler and sublime-text as IDE (I know it's not a real IDE).
I build every so often on my server which is Ubuntu 14.04.3 LTS 32bit with gcc.
I can try to build on Windows 8.1 64bit with Visual Studio if you need me to.

**Comment by koraa** [comment]
++1

**Comment by Fohlen** [comment]
Since Linux Mint 17 is based on Ubuntu 14.04 we can use the same packaging system for both platforms.
I'd like to drop Arch Linux support as there is no major audience for it. Instead I'd like to build RPM packages with our Jenkins, which can be used on a vast majority of distributions (including Cent, Fedora..), although we will need someone to test those (maybe @PowerKiller )

**Comment by PowerKiller** [comment]
Me wants to do Fedora, I regularly use it and can create packages for it.

**Comment by PowerKiller** [comment]
I also have Windows 10, so, I can also provide Windows 10

**Comment by Fohlen** [comment]
Since I am working closely with @Obstriegel to provision a Jenkins instance for Inexor, we're getting close to deploy packages to Launchpad/RHEL repositories. I'd be awesome if you could read/create a script to package RPM bundles :+1:

**Comment by PowerKiller** [comment]
I can do it, I'll try.

**Comment by Croydon** [comment]
I would suggest everyone is adding themselves in the table obove or checking if the current entry is still up to date.
And then I would like to move it to the wiki. After all it is a living document and will get constantly updated.

I guess it is more or less common sense that we are not going to support (_official_) anything older as Windows 7 or Ubuntu 14.04, due to _why the hell should somebody using an older version and playing games with it_ and missing ressources in our team.

/cc @inexor-game/code-developers

**Comment by Fohlen** [comment]
Additionally we should respect that Inexor only builds with GCC5++, which is why we can only support Debian7, Ubuntu 15.10 + upstream.

**Comment by Croydon** [comment]
@Fohlen: It's GCC 4.9+ - and again: there is a difference between running and building.

**Comment by PowerKiller** [comment]
hmm it seems I made it, the RPM packages' script works.

**Comment by bebehei** [comment]
@Powerkiller: how did you fix #286 ? This makes me curious.

**Comment by PowerKiller** [comment]
Mmmmhm, I didn't fix #286

**Comment by Fohlen** [comment]
We've made the decision to officially support these platforms for now:

- Windows 7 and higher
- Ubuntu 16.04 (always the latest platform)

user contributions from other platforms will of course be available for everyone.
In the future we urge to add OSX as a platform.

**Comment by Croydon** [comment]
I still want to clean this up and add it to the wiki. Closing it then.

Also it would be nice if everyone could update his entry in the table.

**Comment by aschaeffer** [comment]
My entry is still up to date

**Comment by aschaeffer** [comment]
But I agree that we should close this issue soon.

**Comment by Fohlen** [comment]
It is noted down in the wiki here, https://github.com/inexorgame/code/wiki/Install-Inexor-in-five-minutes#installation-guide

**Comment by Croydon** [comment]
What you noted there is not even close to having all information.

https://github.com/inexorgame/code/wiki/Platform-Support

**Comment by aschaeffer** [comment]
Good thing we have a wiki page for that.

**Comment by Croydon** [comment]
Yes, I took even more sleep time away from me, after Fohlen pressured me by closing this issues a second time, even I stated clearly then I will do this. That is why we have now a wiki page.

**Comment by aschaeffer** [comment]
I see.
