### ISSUE TITLE
fix Travis CI links

### ISSUE THREAD

**Issue by a-teammate** [inexorgame/code#421]
since we renamed the organisation from inexor-game to inexorgame #404 any link to https://travis-ci.org/inexor-game/code is dead now.. so we should replace it everywhere with https://travis-ci.org/inexorgame/code.

E.g. our wiki and our readme.

you could take a look at https://help.github.com/articles/adding-and-editing-wiki-pages-locally/ and replace that link everywhere (in the wiki + in the code repository)

**Comment by Croydon** [comment]
I have done the entire wiki directly after renaming.
For the readme there is a pull request we should also use for that.

**Comment by Croydon** [comment]
Also not sure why this needed a separate issues, when it is directly connected to #404

**Comment by a-teammate** [comment]
true
